name: Build and Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main  # ou o nome do seu branch principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # ou a versão desejada

      - name: Instalar dependências
        run: |
          gem install bundler
          bundle install

      - name: Construir o site Jekyll
        run: bundle exec jekyll build

      - name: Deploy para o GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
