name: Build and Test Jekyll site

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3' # Versão estável do Ruby para Jekyll

      - name: Instalar dependências
        run: |
          gem install bundler
          bundle install

      - name: Construir o site Jekyll
        run: bundle exec jekyll build